/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emirkartal
 */
public class jfNursePanel extends javax.swing.JFrame {

    /**
     * Creates new form jfNursePanel
     */
    Nurse nurse;

    public Nurse getNurse() {
        return nurse;
    }

    public void setNurse(Nurse nurse) {
        this.nurse = nurse;
        lblTitle1.setText("Nurse "+nurse.getName()+" welcome...");
        
    }
    
    public jfNursePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMyAccount1 = new javax.swing.JButton();
        btnSendRequest1 = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnViewPatient1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMyAccount1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnMyAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        btnMyAccount1.setText("   My Account");
        btnMyAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyAccount1ActionPerformed(evt);
            }
        });

        btnSendRequest1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSendRequest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/friend-request.png"))); // NOI18N
        btnSendRequest1.setText("   Send Request");
        btnSendRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequest1ActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblTitle1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnBack1.setBackground(new java.awt.Color(150, 150, 150));
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnViewPatient1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnViewPatient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/patient.png"))); // NOI18N
        btnViewPatient1.setText("   View Patient");
        btnViewPatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatient1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnViewPatient1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMyAccount1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSendRequest1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack1))
                .addGap(27, 27, 27)
                .addComponent(btnMyAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSendRequest1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyAccount1ActionPerformed
        dispose();
        jfNrAccountPanel nap = new jfNrAccountPanel();
        nap.setNurse(nurse);
        nap.setLocationRelativeTo(null);
        nap.setVisible(true);
    }//GEN-LAST:event_btnMyAccount1ActionPerformed

    private void btnSendRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequest1ActionPerformed
        dispose();
        jfNrRequestPanel nrrp = new jfNrRequestPanel();
        nrrp.setNurse(nurse);
        nrrp.setLocationRelativeTo(null);
        nrrp.setVisible(true);
    }//GEN-LAST:event_btnSendRequest1ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        dispose();
        intro intro = new intro();
        intro.setLocationRelativeTo(null);
        intro.setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnViewPatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatient1ActionPerformed
        dispose();
        jfNrViewPatientPanel nvp = new jfNrViewPatientPanel();
        nvp.setNurse(nurse);
        nvp.setLocationRelativeTo(null);
        nvp.setVisible(true);
    }//GEN-LAST:event_btnViewPatient1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfNursePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfNursePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfNursePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfNursePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfNursePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnMyAccount1;
    private javax.swing.JButton btnSendRequest1;
    private javax.swing.JButton btnViewPatient1;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
